// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdGIaMk1vVXb6mPozUHfrWS76A1p3k8Oc',
    appId: '1:336114413155:web:03830bae04203121b11256',
    messagingSenderId: '336114413155',
    projectId: 'note-app-9f565',
    authDomain: 'note-app-9f565.firebaseapp.com',
    storageBucket: 'note-app-9f565.appspot.com',
    measurementId: 'G-6ERK44M4GX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9G_AgnSdoTqzZdzagpdmUGgD3g-0W1Ck',
    appId: '1:336114413155:android:badab848bbf3a068b11256',
    messagingSenderId: '336114413155',
    projectId: 'note-app-9f565',
    storageBucket: 'note-app-9f565.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASDDVFR41b435QzgzJK0uzs2R7zWSYrwI',
    appId: '1:336114413155:ios:9ca79404a3b2bd74b11256',
    messagingSenderId: '336114413155',
    projectId: 'note-app-9f565',
    storageBucket: 'note-app-9f565.appspot.com',
    iosBundleId: 'com.example.noteAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASDDVFR41b435QzgzJK0uzs2R7zWSYrwI',
    appId: '1:336114413155:ios:9ca79404a3b2bd74b11256',
    messagingSenderId: '336114413155',
    projectId: 'note-app-9f565',
    storageBucket: 'note-app-9f565.appspot.com',
    iosBundleId: 'com.example.noteAppFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdGIaMk1vVXb6mPozUHfrWS76A1p3k8Oc',
    appId: '1:336114413155:web:54f92c3957db8bcdb11256',
    messagingSenderId: '336114413155',
    projectId: 'note-app-9f565',
    authDomain: 'note-app-9f565.firebaseapp.com',
    storageBucket: 'note-app-9f565.appspot.com',
    measurementId: 'G-VF4M95F11D',
  );
}
